import { ShopItem } from '@/types';

export const SHOP_ITEMS: ShopItem[] = [
  // ── Themes ───────────────────────────────────────────────────────────────
  {
    id: 'theme-blood-moon',
    name: 'Blood Moon Theme',
    description: 'A crimson dark theme for seasoned warriors',
    icon: '🌑',
    cost: 200,
    type: 'theme',
    effect: 'blood-moon',
    rarity: 'rare',
  },
  {
    id: 'theme-enchanted-forest',
    name: 'Enchanted Forest',
    description: 'Emerald greens and ancient wood tones',
    icon: '🌲',
    cost: 200,
    type: 'theme',
    effect: 'enchanted-forest',
    rarity: 'rare',
  },
  {
    id: 'theme-celestial',
    name: 'Celestial Realm',
    description: 'Golden starfields and divine light',
    icon: '⭐',
    cost: 500,
    type: 'theme',
    effect: 'celestial',
    rarity: 'epic',
  },
  {
    id: 'theme-abyssal',
    name: 'Abyssal Void',
    description: 'The darkest depths of the underworld',
    icon: '🕳️',
    cost: 750,
    type: 'theme',
    effect: 'abyssal',
    rarity: 'legendary',
  },

  // ── Avatars ───────────────────────────────────────────────────────────────
  {
    id: 'avatar-knight',
    name: 'Iron Knight',
    description: 'A stalwart defender in shining armor',
    icon: '⚔️',
    cost: 50,
    type: 'avatar',
    rarity: 'common',
  },
  {
    id: 'avatar-mage',
    name: 'Arcane Mage',
    description: 'Master of ancient spells and forbidden arts',
    icon: '🧙',
    cost: 50,
    type: 'avatar',
    rarity: 'common',
  },
  {
    id: 'avatar-rogue',
    name: 'Shadow Rogue',
    description: 'Silent and deadly, master of stealth',
    icon: '🗡️',
    cost: 75,
    type: 'avatar',
    rarity: 'common',
  },
  {
    id: 'avatar-paladin',
    name: 'Holy Paladin',
    description: 'Blessed by the gods, protector of the realm',
    icon: '🛡️',
    cost: 150,
    type: 'avatar',
    rarity: 'rare',
  },
  {
    id: 'avatar-dragon',
    name: 'Dragon Rider',
    description: 'Legendary tamer of the ancient dragons',
    icon: '🐉',
    cost: 500,
    type: 'avatar',
    rarity: 'legendary',
  },

  // ── Badges ────────────────────────────────────────────────────────────────
  {
    id: 'badge-first-quest',
    name: 'First Quest',
    description: 'Completed your first quest',
    icon: '🎖️',
    cost: 0,
    type: 'badge',
    rarity: 'common',
  },
  {
    id: 'badge-streak-7',
    name: 'Week Warrior',
    description: '7-day streak achievement',
    icon: '🔥',
    cost: 100,
    type: 'badge',
    rarity: 'rare',
  },
  {
    id: 'badge-streak-30',
    name: 'Iron Will',
    description: '30-day streak — you are unstoppable',
    icon: '💎',
    cost: 300,
    type: 'badge',
    rarity: 'epic',
  },
  {
    id: 'badge-century',
    name: 'Century Slayer',
    description: '100 quests completed',
    icon: '💯',
    cost: 400,
    type: 'badge',
    rarity: 'epic',
  },
  {
    id: 'badge-legendary',
    name: 'Legendary Hero',
    description: 'Reached level 50',
    icon: '👑',
    cost: 1000,
    type: 'badge',
    rarity: 'legendary',
  },

  // ── Boosts ────────────────────────────────────────────────────────────────
  {
    id: 'boost-xp-1',
    name: 'XP Potion',
    description: '+50% XP for 24 hours',
    icon: '🧪',
    cost: 80,
    type: 'boost',
    effect: 'xp-boost-1',
    rarity: 'common',
  },
  {
    id: 'boost-gold-1',
    name: 'Gold Rush',
    description: '+100% Gold for 24 hours',
    icon: '💰',
    cost: 120,
    type: 'boost',
    effect: 'gold-boost-1',
    rarity: 'rare',
  },
];
